### ISSUE TITLE
Make "Meet The Team" cards clickable 

### ISSUE THREAD

**Issue by joeyouss** [devaar100/CodessCafe#4]
### Issue Description:
We currently have a 'Meet the Team' section on our website displaying team members' information. However, the user experience would significantly improve if these team member cards were clickable, leading users to individual profiles or detailed information about each team member when clicked. 

This enhancement would enhance the overall interactivity and engagement of our website, providing visitors with a seamless way to learn more about our team members.

**Comment by Surajit0573** [comment]
Hi @joeyouss, I can make this  "Meet The Team" cards clickable and direct users to the individual profiles. 
Can you please assign me  for this issue !!

**Comment by joeyouss** [comment]
Hi, please make the PR on this repo: https://github.com/Codess-Cafe/Codess-Website/issues/2

@Surajit0573
