### ISSUE TITLE
Add New Team Members

### ISSUE THREAD

**Issue by joeyouss** [devaar100/CodessCafe#5]
### Issue Description:
If there are new team members who have recently joined the organization, their profiles need to be added to the "Meet the Team" section. Include their names, roles, responsibilities, and relevant information to introduce them effectively to website visitors.

**Comment by Tooba-Amjad** [comment]
I'd like to work with this issue. Could you please provide some guidance on where I can find information about the new team?

**Comment by joeyouss** [comment]
@Tooba-Amjad please make a PR here: https://github.com/Codess-Cafe/Codess-Website/issues/3

**Comment by Tooba-Amjad** [comment]
From where can I get the details of new team members?
How could I know about the team members?
