### ISSUE TITLE
Add Horizontal Spacing between Section Heading and Testimonial Cards

### ISSUE THREAD

**Issue by joeyouss** [devaar100/CodessCafe#7]
### Issue Description:
In the testimonial section, there is a need to improve the layout for better readability and visual appeal. Currently, there is insufficient horizontal spacing between the section heading and the testimonial cards, causing a cramped appearance.

To address this issue, developers should adjust the CSS styles or layout to introduce appropriate horizontal spacing. This adjustment will provide a clear visual distinction between the section heading and the testimonial cards, ensuring a more organized and pleasing display.

**Comment by vamsi-spoidey7** [comment]
hey i would like to work on this issue as part of hacktober fest 2023. please assign to me

**Comment by AkashKMathew** [comment]
Hi, I would like to work on this issue. Please assign to me.

**Comment by Tooba-Amjad** [comment]
Issue has been resolved @devaar100 Kindly review 
[Pull Request ](https://github.com/devaar100/CodessCafe/pull/10)

**Comment by joeyouss** [comment]
Hi @Tooba-Amjad , @vamsi-spoidey7 commented on the issue first. @vamsi-spoidey7 are you willing to work on this? If so, please make a PR here: https://github.com/Codess-Cafe/Codess-Website/issues/5

**Comment by Tooba-Amjad** [comment]
Yes I have a huge interest in it 
Also created the pull request
